name: Go Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cross:
    name: Go
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0

    strategy:
      matrix:
        go-version: [1.16, 1.17, 1.18, 1.19]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            '%LocalAppData%\go-build'
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Install golangci-lint
        run: |
          if [ "$(uname)" == "Darwin" ]; then
            # Для macOS
            curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.33.0/golangci-lint-1.33.0-darwin-amd64.tar.gz -o golangci-lint.tar.gz
            tar -xvzf golangci-lint.tar.gz
            mv golangci-lint-*/golangci-lint /usr/local/bin/
            golangci-lint --version
          else
            # Для Linux и Windows
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin v1.33.0
          fi

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          go mod download
          go mod vendor

      - name: Lint and Tests
        run: make
