name: Go Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cross:
    name: Go
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0

    strategy:
      matrix:
        go-version: [1.16, 1.17, 1.18, 1.19]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            '%LocalAppData%\go-build'
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin v1.33.0
          echo "GolangCI-Lint installed at $HOME/go/bin/golangci-lint"

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          go mod download
          go mod vendor

      - name: Lint and Tests
        run: make

      - name: Run tests with Yaegi
        run: make yaegi_test
        env:
          GOPATH: ${{ github.workspace }}/go

      - name: Run plugin tests
        run: make plugin_tests
        env:
          GOPATH: ${{ github.workspace }}/go

      - name: Run Go tests
        run: go test -v -cover ./...
